services:
  web:
    build:
      context: .
      dockerfile: bun_Dockerfile
    ports:
      - '5174:5174'
      - '4983:4983'
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
