services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: bun_Dockerfile
    expose:
      - '5173'
    ports:
      - '5173:5173'
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # Stops log spamming from pgadmin4
    attach: false
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
